Avoid throwing NullPointerExceptions manually.
apache/jspwiki pull request #236
Opened 2022-10-17 19:43 UTC by arturobernalg

2023-03-24 20:20 UTC, juanpablo-santos requested changes
changes requested

2023-03-24 20:20 UTC, juanpablo-santos commented on jspwiki-main/src/main/java/org/apache/wiki/providers/VersioningFileProvider.java
> +                throw new IllegalArgumentException ( "pageName must not be null!" );
I think this is one of those cases where `NullPointerException` really expresses the intent - the field must not be null

2023-03-24 20:20 UTC, juanpablo-santos commented on jspwiki-util/src/main/java/org/apache/wiki/util/TextUtil.java
> +            throw new IllegalArgumentException ( "src must not be null!" );
similar to above comment, perhaps is better to throw a `NullPointerException` informing which field should not be `null`?

2023-04-29 15:01 UTC, arturobernalg commented
@juanpablo-santos 
I agree with your comment. In fact, Joshua Bloch states: -->  Item 72 : Favor the use of standard exceptions:NullPointerException be thrown rather than IllegalArgumentException if caller passes null in some parameters for which null values are prohibited.
I clos the PR

2023-04-29 15:01 UTC, closed without merging